---
title: "SDS-mp3"
author: "Aoi Ogawa, Stella Li, Ester Zhao"
date: "4/3/2018"
output: 
  html_document :
    code_folding : hide
---

```{r, message = FALSE, warning = FALSE}

library(tidyverse)
library(sf)
library(macleish)
library(leaflet)

```

<br>




```{r, message = FALSE, warning = FALSE}
# getting the table of maple syrup data and weather data from macleish

macleish <- etl("macleish")

str(macleish)

macleish %>%
etl_extract() %>%
etl_transform() %>%
etl_load()

whately <- macleish %>%
tbl("whately")

weather <- data.frame(whately)

weather_time <- data.frame(whately)

maple_sap <- data.frame(maple_sap)

```


```{r, message = FALSE, warning = FALSE}
# Mappping the maple tree forests using leaflet
maple_forest <- macleish_layers[["forests"]] %>% 
  filter(VegType_21 == "3")

birch_maple_forest <- macleish_layers[["forests"]] %>% 
  filter(VegType_21 == "13" )


leaflet() %>%
  addTiles() %>%
  addPolygons(data = maple_forest, color = "red") %>%
  addPolygons(data = birch_maple_forest, color = "yellow")
```


```{r, message = FALSE, warning = FALSE}
#Separating the date into year, month, and day for clarity
#Filter out NA data for sap

sap <- maple_sap %>% 
  filter(!is.na(sap)) %>%
  separate(when, c("year", "month", "day"), sep = "-")

f_weather <- weather_time %>% 
  separate(when,c("year", "month", "day"), sep = "-") %>%
  separate(day, c("day", "time"), sep = "T")

```



```{r, message = FALSE, warning = FALSE}
#Filter out irrelevant data (only temp and sap is needed)

f_weather$wind_speed <- NULL
f_weather$wind_dir <- NULL
f_weather$rel_humidity <- NULL
f_weather$pressure <- NULL
f_weather$solar_radiation <- NULL
f_weather$rainfall <- NULL

sap_weather <- inner_join(f_weather, sap) 

sap_weather$Comments <- NULL

```


```{r, message = FALSE, warning = FALSE}
#Get the average daytime and nighttime temperatures for each day

daytime_sap_data <- sap_weather %>%
  group_by(year,month,day) %>%
  filter(time >= "06:00:00Z" &
           time <="18:00:00Z") %>% 
  summarize(day_avg_temp = mean(temperature))


nighttime_sap_data <- sap_weather %>%
    group_by(year,month,day) %>%
  filter(time >= "00:00:00Z" &
           time < "06:00:00Z" |
           time > "18:00:00Z" &
           time < "24:00:00Z") %>%
  summarize(night_avg_temp = mean(temperature))
  
#Join daytime and nighttime average temperatures into one data frame
#Calculate the difference between daytime and nighttime average temperatures for each day

final_sap <- inner_join(daytime_sap_data, nighttime_sap_data) %>%
  mutate(temp_diff = day_avg_temp - night_avg_temp)

final_sap <-inner_join(final_sap, sap)


# Join the year, month, and day columns back into one date column
  
final_sap$date <- paste0(final_sap$year, final_sap$month, final_sap$day)
final_sap$date <- ymd(final_sap$date)

final_sap$day <- NULL
final_sap$year <- NULL 
final_sap$month <- NULL 
final_sap$Comments <- NULL


final_sap <- final_sap[c("date", "day_avg_temp", "night_avg_temp", "temp_diff", "sap", "People")]
  
#Plot the sap yield and the difference in temperature over time
ggplot(final_sap, aes (x = date))+ 
  geom_line(aes(y = temp_diff), colour = "blue") +
  geom_line(aes(y = sap), colour = "orange") +
  labs(x = "Date", y = "Difference in Tempreture") +
  scale_y_continuous(sec.axis = sec_axis(~.*5, name = "Sap Yield")) 
  
  
    
         

```
